version: '3.1'
services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    ports:
      - '3000:3000'
    command: npm run dev
    links:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - 'mongo'
    networks:
      - backend

  mongo:
    container_name: 'mongonode'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: local
      MONGO_HOST_IP: mongonode
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge