version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev    
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - database
      - redis
    depends_on:
      - database
      - redis

  database:
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - 27092:27017
  redis:
     image: redis
     ports:
       - 6391:6379